In [1]:
!pip install transformers==4.57.3 trl accelerate peft bitsandbytes datasets huggingface_hub fpdf
!pip install --force-reinstall charset-normalizer

import time
import re
import torch
import textwrap
from datasets import load_dataset, Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, BitsAndBytesConfig, AutoConfig
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training
from trl import SFTTrainer
from fpdf import FPDF
from google.colab import drive
from huggingface_hub import login

# Google Drive is mounted and Hugging Face authentication is established
drive.mount('/content/drive', force_remount=True)
login(token="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")

# --- DYNAMIC HARDWARE DETECTION ---
if torch.cuda.is_available() and torch.cuda.is_bf16_supported():
    COMPUTE_DTYPE = torch.bfloat16
    USE_FP16 = False
    USE_BF16 = True
    print("Hardware supports bfloat16. Using bf16 for optimal LLaMA-3 training.")
else:
    COMPUTE_DTYPE = torch.float16
    USE_FP16 = True
    USE_BF16 = False
    print("Hardware does not support bfloat16 natively. Falling back to fp16 with strict casting.")

class DataProcessor:
    """Methods for evaluating model output against ground truth and extracting schema-specific fields."""

    @staticmethod
    def extract_fields(dataset_name, sample):
        if dataset_name == "gsm8k":
            return sample["question"], sample["answer"]
        elif dataset_name == "superglue":
            passage = sample.get("passage", "")
            question = sample.get("question", "")
            combined_input = f"{passage}\nQuestion: {question}" if passage else question
            return combined_input, str(sample.get("label", ""))
        elif dataset_name == "financial_phrasebank":
            return sample.get("sentence", ""), str(sample.get("label", ""))
        elif dataset_name == "raft":
            return sample.get("Sentence", ""), str(sample.get("Label", ""))
        elif dataset_name == "ifbench":
            instruction = sample.get("instruction", sample.get("prompt", sample.get("question", "")))
            response = sample.get("response", sample.get("answer", sample.get("label", "")))
            return instruction, response
        else:
            return str(sample), str(sample)

    @staticmethod
    def evaluate(dataset_name, generation, ground_truth):
        if dataset_name == "gsm8k":
            truth_match = re.search(r'####\s*(.+)$', str(ground_truth))
            truth_value = truth_match.group(1).strip() if truth_match else str(ground_truth).strip()
            generation_numbers = re.findall(r'-?\d+(?:,\d+)*(?:\.\d+)?', generation)
            generation_value = generation_numbers[-1] if generation_numbers else ""
            return truth_value == generation_value
        else:
            return str(ground_truth).strip().lower() in generation.strip().lower()

class BaselineExecutor:
    def __init__(self, model_id="meta-llama/Meta-Llama-3-8B-Instruct"):
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=COMPUTE_DTYPE
        )

        print(f"Loading {model_id}...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)
        self.tokenizer.pad_token = self.tokenizer.eos_token

        config = AutoConfig.from_pretrained(model_id)
        config.torch_dtype = COMPUTE_DTYPE

        self.model = AutoModelForCausalLM.from_pretrained(
            model_id,
            config=config,
            quantization_config=bnb_config,
            device_map="auto",
            torch_dtype=COMPUTE_DTYPE
        )

        # Aggressively purge residual bfloat16 tensors (like rotary_emb.inv_freq) if hardware requires fp16
        if USE_FP16:
            for name, buffer in self.model.named_buffers():
                if buffer.dtype == torch.bfloat16:
                    buffer.data = buffer.data.to(torch.float16)
            for name, param in self.model.named_parameters():
                if param.dtype == torch.bfloat16:
                    param.data = param.data.to(torch.float16)

    def execute_lora_finetuning(self, query, context_examples):
        self.model = prepare_model_for_kbit_training(self.model, use_gradient_checkpointing=False)

        train_texts = [f"{ex}{self.tokenizer.eos_token}" for ex in context_examples]
        train_dataset = Dataset.from_dict({"text": train_texts})

        def tokenize_map(examples):
            return self.tokenizer(examples["text"], truncation=True, max_length=256, padding="max_length")

        tokenized_ds = train_dataset.map(tokenize_map, batched=True, remove_columns=["text"])

        lora_config = LoraConfig(
            r=8, lora_alpha=16, target_modules=["q_proj", "v_proj"],
            lora_dropout=0.05, bias="none", task_type=TaskType.CAUSAL_LM
        )

        peft_model = get_peft_model(self.model, lora_config)

        training_args = TrainingArguments(
            output_dir="./lora_tmp",
            per_device_train_batch_size=1,
            gradient_accumulation_steps=4,
            num_train_epochs=1,
            fp16=USE_FP16,
            bf16=USE_BF16,
            logging_steps=1,
            report_to="none",
            use_cpu=False
        )

        trainer = SFTTrainer(
            model=peft_model,
            train_dataset=tokenized_ds,
            args=training_args
        )

        trainer.train()

        peft_model.eval()
        inputs = self.tokenizer(query, return_tensors="pt").to(peft_model.device)

        start_time = time.perf_counter()
        with torch.no_grad():
            outputs = peft_model.generate(**inputs, max_new_tokens=20, pad_token_id=self.tokenizer.eos_token_id)
        latency_ms = (time.perf_counter() - start_time) * 1000

        response = self.tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)

        peft_model.unload()
        return response, latency_ms

def load_all_datasets():
    datasets_dict = {}
    try:
        datasets_dict["gsm8k"] = load_dataset("openai/gsm8k", "main", split="train")
    except Exception as e:
        print(f"Skipping GSM8K: {e}")

    try:
        datasets_dict["superglue"] = load_dataset("super_glue", "boolq", split="validation")
    except Exception as e:
        print(f"Skipping SuperGLUE: {e}")

    try:
        datasets_dict["financial_phrasebank"] = load_dataset("financial_phrasebank", "sentences_allagree", split="train")
    except Exception as e:
        print(f"Skipping Financial PhraseBank: {e}")

    try:
        datasets_dict["raft"] = load_dataset("ought/raft", "ade_corpus_v2", split="train")
    except Exception as e:
        print(f"Skipping RAFT: {e}")

    try:
        datasets_dict["ifbench"] = load_dataset("Muennighoff/IFEval", split="train")
    except Exception as e:
        print(f"Skipping IFBench: {e}")

    return datasets_dict

def run_evaluation_harness():
    executor = BaselineExecutor()
    processor = DataProcessor()
    datasets_dict = load_all_datasets()

    report_lines = []

    for dataset_name, dataset in datasets_dict.items():
        header = f"\n{'='*50}\nEvaluating Dataset: {dataset_name.upper()}\n{'='*50}"
        print(header)
        report_lines.append(header)

        for n in [16, 32, 64, 128, 256]:
            print(f"\n[Dataset: {dataset_name.upper()} | N={n}] Processing...")

            if n >= len(dataset):
                print(f"  -> Insufficient data for N={n}. Skipping.")
                continue

            context = []
            for i in range(n):
                sample = dataset[i]
                q, a = processor.extract_fields(dataset_name, sample)
                context.append(f"Input: {q}\nOutput: {a}")

            test_sample = dataset[n]
            raw_query, truth = processor.extract_fields(dataset_name, test_sample)
            query = f"Input: {raw_query}\nOutput:"

            resp, lat = executor.execute_lora_finetuning(query, context)
            match = processor.evaluate(dataset_name, resp, truth)

            res_str = f"  -> Latency: {lat:.2f}ms | Exact Match: {match}"
            print(res_str)
            report_lines.append(f"[{dataset_name.upper()} | N={n}] Latency: {lat:.2f}ms | Match: {match}")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 10, txt="Evaluation Report - Stratified LoRA (Comprehensive)", ln=True, align='C')
    pdf.ln(5)

    for line in report_lines:
        wrapped_lines = textwrap.wrap(line, width=90)
        for wrapped in wrapped_lines:
            safe_txt = wrapped.encode('latin-1', 'replace').decode('latin-1')
            pdf.cell(0, 8, txt=safe_txt, ln=True)

    save_path = "/content/drive/MyDrive/stratified_lora_results.pdf"
    pdf.output(save_path)
    print(f"\nReport successfully saved to Google Drive: {save_path}")

if __name__ == "__main__":
    run_evaluation_harness()

Requirement already satisfied: transformers==4.57.3 in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (0.28.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.5.0)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Requirement already satisfied: fpdf in /usr/local/lib/python3.12/dist-packages (1.7.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (3.24.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2024.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.3) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.3) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Collecting charset-normalizer
  Using cached charset_normalizer-3.4.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (37 kB)
Using cached charset_normalizer-3.4.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (153 kB)
Installing collected packages: charset-normalizer
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.4.4
    Uninstalling charset-normalizer-3.4.4:
      Successfully uninstalled charset-normalizer-3.4.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.2.0 which is incompatible.
Successfully installed charset-normalizer-3.4.4
Mounted at /content/drive
Hardware supports bfloat16. Using bf16 for optimal LLaMA-3 training.
Loading meta-llama/Meta-Llama-3-8B-Instruct...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Using the latest cached version of the dataset since financial_phrasebank couldn't be found on the Hugging Face Hub
WARNING:datasets.load:Using the latest cached version of the dataset since financial_phrasebank couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'sentences_allagree' at /root/.cache/huggingface/datasets/financial_phrasebank/sentences_allagree/1.0.0/550bde12e6c30e2674da973a55f57edde5181d53f5a5a34c1531c53f93b7e141 (last modified on Sun Feb 22 04:55:20 2026).
WARNING:datasets.packaged_modules.cache.cache:Found the latest cached dataset configuration 'sentences_allagree' at /root/.cache/huggingface/datasets/financial_phrasebank/sentences_allagree/1.0.0/550bde12e6c30e2674da973a55f57edde5181d53f5a5a34c1531c53f93b7e141 (last modified on Sun Feb 22 04:55:20 2026).
Using the latest cached version of the dataset since ought/raft couldn't be found on the Hugging Face Hub
WARNING:datasets.load:Using the latest cached version of the dataset since ought/raft couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'ade_corpus_v2' at /root/.cache/huggingface/datasets/ought___raft/ade_corpus_v2/1.1.0/9ee50172ea9afda2f1033c6f1b986e568b862fb3 (last modified on Sun Feb 22 04:55:22 2026).
WARNING:datasets.packaged_modules.cache.cache:Found the latest cached dataset configuration 'ade_corpus_v2' at /root/.cache/huggingface/datasets/ought___raft/ade_corpus_v2/1.1.0/9ee50172ea9afda2f1033c6f1b986e568b862fb3 (last modified on Sun Feb 22 04:55:22 2026).

Skipping IFBench: Dataset 'Muennighoff/IFEval' doesn't exist on the Hub or cannot be accessed.

==================================================
Evaluating Dataset: GSM8K
==================================================

[Dataset: GSM8K | N=16] Processing...

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/16 [00:00<?, ? examples/s]

  -> Latency: 619.92ms | Exact Match: False

[Dataset: GSM8K | N=32] Processing...

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/32 [00:00<?, ? examples/s]

  -> Latency: 538.07ms | Exact Match: True

[Dataset: GSM8K | N=64] Processing...

Map:   0%|          | 0/64 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/64 [00:00<?, ? examples/s]

  -> Latency: 523.97ms | Exact Match: False

[Dataset: GSM8K | N=128] Processing...

Map:   0%|          | 0/128 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/128 [00:00<?, ? examples/s]

  -> Latency: 523.48ms | Exact Match: False

[Dataset: GSM8K | N=256] Processing...

Map:   0%|          | 0/256 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/256 [00:00<?, ? examples/s]

  -> Latency: 525.85ms | Exact Match: False

==================================================
Evaluating Dataset: SUPERGLUE
==================================================

[Dataset: SUPERGLUE | N=16] Processing...

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/16 [00:00<?, ? examples/s]

  -> Latency: 529.37ms | Exact Match: False

[Dataset: SUPERGLUE | N=32] Processing...

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/32 [00:00<?, ? examples/s]

  -> Latency: 527.06ms | Exact Match: False

[Dataset: SUPERGLUE | N=64] Processing...

Map:   0%|          | 0/64 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/64 [00:00<?, ? examples/s]

  -> Latency: 526.67ms | Exact Match: True

[Dataset: SUPERGLUE | N=128] Processing...

Map:   0%|          | 0/128 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/128 [00:00<?, ? examples/s]

  -> Latency: 534.42ms | Exact Match: False

[Dataset: SUPERGLUE | N=256] Processing...

Map:   0%|          | 0/256 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/256 [00:00<?, ? examples/s]

  -> Latency: 522.18ms | Exact Match: False

==================================================
Evaluating Dataset: FINANCIAL_PHRASEBANK
==================================================

[Dataset: FINANCIAL_PHRASEBANK | N=16] Processing...

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/16 [00:00<?, ? examples/s]

  -> Latency: 530.38ms | Exact Match: False

[Dataset: FINANCIAL_PHRASEBANK | N=32] Processing...

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/32 [00:00<?, ? examples/s]

  -> Latency: 524.85ms | Exact Match: False

[Dataset: FINANCIAL_PHRASEBANK | N=64] Processing...

Map:   0%|          | 0/64 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/64 [00:00<?, ? examples/s]

  -> Latency: 521.81ms | Exact Match: False

[Dataset: FINANCIAL_PHRASEBANK | N=128] Processing...

Map:   0%|          | 0/128 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/128 [00:00<?, ? examples/s]

  -> Latency: 525.42ms | Exact Match: True

[Dataset: FINANCIAL_PHRASEBANK | N=256] Processing...

Map:   0%|          | 0/256 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/256 [00:00<?, ? examples/s]

  -> Latency: 526.11ms | Exact Match: True

==================================================
Evaluating Dataset: RAFT
==================================================

[Dataset: RAFT | N=16] Processing...

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/16 [00:00<?, ? examples/s]

  -> Latency: 530.22ms | Exact Match: False

[Dataset: RAFT | N=32] Processing...

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Truncating train dataset:   0%|          | 0/32 [00:00<?, ? examples/s]

  -> Latency: 525.85ms | Exact Match: False

[Dataset: RAFT | N=64] Processing...
  -> Insufficient data for N=64. Skipping.

[Dataset: RAFT | N=128] Processing...
  -> Insufficient data for N=128. Skipping.

[Dataset: RAFT | N=256] Processing...
  -> Insufficient data for N=256. Skipping.

Report successfully saved to Google Drive: /content/drive/MyDrive/stratified_lora_results.pdf