In [1]:
!pip install transformers==4.51.0 trl==0.12.0 accelerate>=0.33.0 peft==0.14.0 bitsandbytes datasets==3.6.0 huggingface_hub fpdf pyreft matplotlib protobuf==3.20.3 pandas --upgrade
!pip install --force-reinstall charset-normalizer
!pip uninstall -y torch_xla

import time
import torch
import numpy as np
import os
import logging
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset, Dataset
from huggingface_hub import login
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    TrainingArguments,
    Trainer
)
from peft import get_peft_model, PrefixTuningConfig, TaskType
from sklearn.metrics import accuracy_score
from fpdf import FPDF
from torch.optim import AdamW

# System logs are configured for execution tracking
logging.basicConfig(filename='project_execution.log', level=logging.INFO)

def compute_metrics(eval_pred):
    """Evaluation metrics are calculated for the classification tasks."""
    predictions, labels = eval_pred
    preds = np.argmax(predictions, axis=1)
    return {"accuracy": accuracy_score(labels, preds)}

def plot_loss_curves(log_history, model_name, ds_name, N, output_dir):
    """Training loss curves are generated and saved as images."""
    train_loss = [log['loss'] for log in log_history if 'loss' in log]
    steps = [log['step'] for log in log_history if 'loss' in log]

    if train_loss:
        plt.figure(figsize=(10, 6))
        plt.plot(steps, train_loss, marker='o', linestyle='-', color='tab:red', label='Training Loss')
        plt.xlabel('Training Steps')
        plt.ylabel('Loss')

        safe_model_name = model_name.replace("/", "_")
        plt.title(f'Training Loss Convergence\nModel: {model_name} | Dataset: {ds_name} | N={N}')
        plt.legend()
        plt.grid(True)

        plot_filename = f"{output_dir}/loss_curve_{safe_model_name}_{ds_name}_N{N}.png"
        plt.savefig(plot_filename)
        plt.close()
        return plot_filename
    return None

def execute_ptuning_pipeline():
    """The complete P-Tuning v2 evaluation pipeline is executed."""

    os.makedirs(os.path.expanduser('~/.kaggle'), exist_ok=True)
    login(token="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")

    output_dir = './CS224N_Project'
    os.makedirs(output_dir, exist_ok=True)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Arial", size=14, style='B')
    pdf.cell(200, 10, txt="Step-by-Step Evaluation Metrics", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf_filepath = f"{output_dir}/comprehensive_tradeoff_metrics.pdf"

    model_names = ["meta-llama/Meta-Llama-3-8B", "Qwen/Qwen3-8B"]

    datasets_info = {
        "Financial_PhraseBank": ("financial_phrasebank", "sentences_allagree", 3, 'sentence', None),
        "SuperGLUE_RTE": ("super_glue", "rte", 2, 'premise', 'hypothesis')
    }

    N_values = [16, 32, 64, 128, 256]
    seeds = [42]

    peft_config = PrefixTuningConfig(
        task_type=TaskType.SEQ_CLS,
        num_virtual_tokens=20
    )

    aggregated_results = {d: {m: {n: {} for n in N_values} for m in model_names} for d in datasets_info}
    loss_plot_files = []

    for model_name in model_names:
        print(f"\nEvaluating model: {model_name}")
        tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        tokenizer.padding_side = 'left'

        for ds_key, (ds_path, ds_name, num_labels, text_col1, text_col2) in datasets_info.items():
            print(f"  Dataset: {ds_key}")
            raw_dataset = load_dataset(ds_path, ds_name, trust_remote_code=True)

            split_dataset = raw_dataset['train'].train_test_split(test_size=0.2, seed=42)
            eval_data = split_dataset['test']

            def preprocess_fn(examples):
                if text_col2:
                    return tokenizer(examples[text_col1], examples[text_col2], truncation=True, max_length=128, padding='max_length')
                return tokenizer(examples[text_col1], truncation=True, max_length=128, padding='max_length')

            tokenized_eval = eval_data.map(preprocess_fn, batched=True)

            for N in N_values:
                print(f"    Evaluating N={N}")
                n_metrics = {"accuracy": [], "loss": [], "latency": [], "throughput": [], "vram": []}

                for seed in seeds:
                    df = split_dataset['train'].to_pandas()
                    label_col = 'label' if 'label' in df.columns else df.columns[-1]

                    try:
                        samples_per_class = max(1, N // num_labels)
                        stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)
                    except ValueError:
                        stratified_df = df.sample(n=N, random_state=seed)

                    train_subset = Dataset.from_pandas(stratified_df)
                    tokenized_train = train_subset.map(preprocess_fn, batched=True)

                    model = AutoModelForSequenceClassification.from_pretrained(
                        model_name,
                        num_labels=num_labels,
                        trust_remote_code=True,
                        pad_token_id=tokenizer.pad_token_id,
                        torch_dtype=torch.bfloat16
                    )
                    model = get_peft_model(model, peft_config)

                    for name, param in model.named_parameters():
                        if "score" in name:
                            param.requires_grad = True

                    prefix_params = []
                    classifier_params = []
                    for name, param in model.named_parameters():
                        if param.requires_grad:
                            if "score" in name:
                                classifier_params.append(param)
                            else:
                                prefix_params.append(param)

                    optimizer_grouped_parameters = [
                        {"params": prefix_params, "lr": 2e-2},
                        {"params": classifier_params, "lr": 1e-4}
                    ]

                    optimizer = AdamW(optimizer_grouped_parameters, weight_decay=0.01)

                    training_args = TrainingArguments(
                        output_dir="./peft_results",
                        per_device_train_batch_size=4,
                        per_device_eval_batch_size=8,
                        learning_rate=2e-2,
                        do_train=True,
                        do_eval=True,
                        num_train_epochs=10,
                        report_to="none",
                        logging_dir="./logs",
                        logging_steps=10,
                        max_grad_norm=1.0,
                        bf16=True
                    )

                    trainer = Trainer(
                        model=model,
                        args=training_args,
                        train_dataset=tokenized_train,
                        eval_dataset=tokenized_eval,
                        compute_metrics=compute_metrics,
                        optimizers=(optimizer, None)
                    )

                    trainer.train()

                    loss_file = plot_loss_curves(trainer.state.log_history, model_name, ds_key, N, output_dir)
                    if loss_file:
                        loss_plot_files.append(loss_file)

                    # Final loss extraction
                    train_loss_history = [log['loss'] for log in trainer.state.log_history if 'loss' in log]
                    final_loss = train_loss_history[-1] if train_loss_history else 0.0
                    n_metrics["loss"].append(final_loss)

                    if torch.cuda.is_available():
                        torch.cuda.reset_peak_memory_stats()

                    start_time = time.time()
                    metrics = trainer.evaluate()
                    total_time = time.time() - start_time

                    peak_vram = torch.cuda.max_memory_allocated() / (1024**3) if torch.cuda.is_available() else 0.0

                    latency = (total_time / len(tokenized_eval)) * 1000
                    throughput = len(tokenized_eval) / total_time

                    n_metrics["accuracy"].append(metrics["eval_accuracy"])
                    n_metrics["latency"].append(latency)
                    n_metrics["throughput"].append(throughput)
                    n_metrics["vram"].append(peak_vram)

                aggregated_results[ds_key][model_name][N] = {
                    "accuracy": np.mean(n_metrics["accuracy"]),
                    "loss": np.mean(n_metrics["loss"]),
                    "latency": np.mean(n_metrics["latency"]),
                    "throughput": np.mean(n_metrics["throughput"]),
                    "peak_vram_gb": np.mean(n_metrics["vram"])
                }

                pdf.set_font("Arial", size=10, style='B')
                pdf.cell(200, 8, txt=f"Model: {model_name} | Dataset: {ds_key} | N: {N}", ln=True)
                pdf.set_font("Arial", size=9)
                step_metrics = aggregated_results[ds_key][model_name][N]
                pdf.cell(200, 6, txt=f"  Acc: {step_metrics['accuracy']:.4f} | Loss: {step_metrics['loss']:.4f} | Latency: {step_metrics['latency']:.2f}ms | VRAM: {step_metrics['peak_vram_gb']:.2f}GB", ln=True)

    # Added loss to tradeoff plots
    metrics_to_plot = {
        "accuracy": "Accuracy",
        "loss": "Final Training Loss",
        "latency": "Latency (ms)",
        "throughput": "Throughput (samples/sec)",
        "peak_vram_gb": "Peak VRAM (GB)"
    }

    for ds_key, models_res in aggregated_results.items():
        for metric_key, metric_label in metrics_to_plot.items():
            pdf.add_page()
            pdf.set_font("Arial", size=14, style='B')
            pdf.cell(200, 10, txt=f"Tradeoff Analysis: {ds_key} - {metric_label}", ln=True, align='C')

            fig, ax1 = plt.subplots(figsize=(10, 6))
            ax1.set_xlabel('N (shots / training examples)')
            ax1.set_ylabel(metric_label, color='black')

            colors = ['tab:blue', 'tab:orange', 'tab:green']

            for idx, (model_name, n_data) in enumerate(models_res.items()):
                x_N = sorted(list(n_data.keys()))
                y_val = [n_data[n][metric_key] for n in x_N]

                ax1.plot(x_N, y_val, marker='o', color=colors[idx % len(colors)], label=f'{model_name.split("/")[-1]}')

            ax1.tick_params(axis='y', labelcolor='black')
            ax1.legend(loc='upper right' if metric_key == "loss" else 'lower right')

            plt.title(f'{metric_label} Scaling\nDataset: {ds_key}')
            fig.tight_layout()

            plot_filename = f"{output_dir}/plot_{metric_key}_{ds_key}.png"
            plt.savefig(plot_filename)
            plt.close()

            pdf.image(plot_filename, x=15, y=30, w=180)

    if loss_plot_files:
        pdf.add_page()
        pdf.set_font("Arial", size=14, style='B')
        pdf.cell(200, 10, txt="Training Loss Curves", ln=True, align='C')
        y_offset = 30
        for plot_file in loss_plot_files:
            if y_offset > 200:
                pdf.add_page()
                y_offset = 20
            pdf.image(plot_file, x=15, y=y_offset, w=180)
            y_offset += 120

    pdf.output(pdf_filepath)
    print(f"\nEvaluation complete. Final PDF generated and updated at: {pdf_filepath}")

if __name__ == "__main__":
    execute_ptuning_pipeline()

Collecting charset-normalizer
  Using cached charset_normalizer-3.4.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (37 kB)
Using cached charset_normalizer-3.4.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (153 kB)
Installing collected packages: charset-normalizer
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.4.4
    Uninstalling charset-normalizer-3.4.4:
      Successfully uninstalled charset-normalizer-3.4.4
Successfully installed charset-normalizer-3.4.4
WARNING: Skipping torch_xla as it is not installed.

Evaluating model: meta-llama/Meta-Llama-3-8B

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

  Dataset: Financial_PhraseBank
    Evaluating N=16

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=32

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=64

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/63 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=128

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/126 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=256

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/255 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

  Dataset: SuperGLUE_RTE

Map:   0%|          | 0/498 [00:00<?, ? examples/s]

    Evaluating N=16

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=32

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=64

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/64 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=128

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/128 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=256

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/256 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

Evaluating model: Qwen/Qwen3-8B
  Dataset: Financial_PhraseBank

Map:   0%|          | 0/453 [00:00<?, ? examples/s]

    Evaluating N=16

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/15 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/peft/mapping.py:185: UserWarning: The PEFT config's `base_model_name_or_path` was renamed from 'meta-llama/Meta-Llama-3-8B' to 'Qwen/Qwen3-8B'. Please ensure that the correct base model is loaded when loading this checkpoint.
  warnings.warn(
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=32

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=64

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/63 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=128

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/126 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=256

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/255 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

  Dataset: SuperGLUE_RTE

Map:   0%|          | 0/498 [00:00<?, ? examples/s]

    Evaluating N=16

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=32

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=64

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/64 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=128

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/128 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

    Evaluating N=256

/tmp/ipython-input-25313/23363996.py:123: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_df = df.groupby(label_col, group_keys=False).apply(lambda x: x.sample(n=min(len(x), samples_per_class), random_state=seed)).head(N)

Map:   0%|          | 0/256 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Some weights of Qwen3ForSequenceClassification were not initialized from the model checkpoint at Qwen/Qwen3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

Evaluation complete. Final PDF generated and updated at: ./CS224N_Project/comprehensive_tradeoff_metrics.pdf